development:
  adapter: postgresql
  database: ahnp_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ahnp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ahnp_production
  pool: 5
  timeout: 5000